/* [Programmers] 131533. 상품 별 오프라인 매출 구하기 */

SELECT PRODUCT.PRODUCT_CODE, SUM(PRODUCT.PRICE * OFFLINE_SALE.SALES_AMOUNT) as SALES
FROM PRODUCT
INNER JOIN OFFLINE_SALE
ON PRODUCT.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID
GROUP BY PRODUCT.PRODUCT_CODE
ORDER BY SALES desc, PRODUCT.PRODUCT_CODE asc;