/* [Programmers] 133025. 과일로 만든 아이스크림 고르기 */

SELECT B.FLAVOR
FROM FIRST_HALF as A, ICECREAM_INFO as B
WHERE A.FLAVOR = B.FLAVOR
AND A.TOTAL_ORDER > 3000
AND B.INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC;