/* [Programmers] 164670. 조건에 맞는 사용자 정보 조회하기 */

SELECT USER.USER_ID, USER.NICKNAME,
    CONCAT_WS(" ", USER.CITY, USER.STREET_ADDRESS1, USER.STREET_ADDRESS2) as 전체주소,
    CONCAT_WS("-",
        SUBSTR(USER.TLNO, 1, 3),
        SUBSTR(USER.TLNO, 4, LENGTH(USER.TLNO) - 7),
        SUBSTR(USER.TLNO, -4, 4)) as 전화번호
FROM USED_GOODS_BOARD as BOARD
JOIN USED_GOODS_USER as USER
ON BOARD.WRITER_ID = USER.USER_ID
GROUP BY USER.USER_ID
HAVING COUNT(USER.USER_ID) >= 3
ORDER BY USER.USER_ID desc;