/* [Programmers] 164671. 조회수가 가장 많은 중고거래 게시판의 첨부파일 조회하기 */

SELECT CONCAT_WS("",
    "/home/grep/src", "/",
    FILE.BOARD_ID, "/",
    FILE.FILE_ID,
    FILE.FILE_NAME,
    FILE.FILE_EXT
) as FILE_PATH
FROM USED_GOODS_BOARD as BOARD
INNER JOIN USED_GOODS_FILE as FILE
ON BOARD.BOARD_ID = FILE.BOARD_ID
WHERE BOARD.VIEWS = (
    SELECT MAX(USED_GOODS_BOARD.VIEWS)
    FROM USED_GOODS_BOARD
)
ORDER BY FILE.FILE_ID desc;