/* [Programmers] 59412. 입양 시각 구하기(1) */

SELECT HOUR, COUNT(*)
FROM (
    SELECT HOUR(DATETIME) as HOUR
    FROM ANIMAL_OUTS
    WHERE HOUR(DATETIME) BETWEEN 9 AND 19
) as ANIMAL_HOUR_TABLE
GROUP BY HOUR
ORDER BY HOUR;